version: "3"

services:
  mysql:
    image: mysql:8.0.30-debian
    restart: always
    ports:
      - 3305:3306
    environment:
      MYSQL_DATABASE: routes
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init-tables.sql:/docker-entrypoint-initdb.d/init-tables.sql

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
